### ISSUE TITLE
Composer extension requirement

### ISSUE THREAD

**Issue by rogeriolino** [kafoso/doctrine-firebird-driver#1]
Add ext requirement on `composer.json`.

Example:

    ext-interbase: "*"

**Comment by kafoso** [comment]
Thanks for the heads-up. It of course needs to be there.

I'll add it in a minor version.

**Comment by kafoso** [comment]
Coming to think of it, adding it to `require` will demand that a host OS has the extension installed. That's not a limitation that I want to impose.

It effectively means it'll become uninstallable through composer on the host OS when running `composer install` without `--ignore-platform-reqs`. Said option shouldn't be utilized unless you **really** know what you're doing.

It might only - in a development context (i.e. not production, staging, or test) - be needed in a VM guest OS (e.g. Docker, Vagrant, or XAMPP). Similar to how the test suite in this library is installed through a Vagrantfile.

-----

I've added the following to README.md under Requirements:

> ibase PHP extension (http://php.net/manual/en/book.ibase.php). Only needed on guest OS, e.g. a VM installed through Docker, Vagrant, or XAMPP.

d7b6d483d94a53e2461c973099b372c12cdcd729

Will be released with the next version.
