### ISSUE TITLE
Problem on some serveur: General error: -303 Dynamic SQL Error SQL error code = -303 arithmetic exception, numeric overflow, or string truncation

### ISSUE THREAD

**Issue by julienheroux** [kafoso/doctrine-firebird-driver#11]
Hi,
On some serveur i've got the error:
General error: -303 Dynamic SQL Error SQL error code = -303 arithmetic exception, numeric overflow, or string truncation
with standard verison of bundle and with the pdo version actually in pull request.
The error is present when a query is made with a prepare and then execute with an integer parameters.
The problem is present on 2 of my server in php7.2.34 and not present on other in same os and php version.
I really don't understand what is the problem.
Can someone help me please ?
Thanks

**Comment by kafoso** [comment]
Hello @julienheroux 

Could you please provide the SQL string or a derivative of it, that still works and where the error still occurs? I take that all parameters are integers, as you describe?

This might be helpful to you: http://www.firebirdfaq.org/faq79/

Things like division by zero and arithmetic overflow may cause the error. It would seem the error is in the SQL or its contents. Not with this driver.

**Comment by julienheroux** [comment]
Hi,
The problem disappears when i've update friebrid database from 2.1 to 2.5.9
Thanks
