### ISSUE TITLE
Upgrading to latest doctrine version

### ISSUE THREAD

**Issue by e-belair** [kafoso/doctrine-firebird-driver#2]
Is that possible to upgrade to the most recent version of doctrine ?

**Comment by kafoso** [comment]
Yes. By "doctrine" you mean the ORM (https://github.com/doctrine/doctrine2), which is currently at 2.6.2?

I suppose I could bump the version numbers to follow those of Doctrine releases, more or less.

**Comment by e-belair** [comment]
Yes it is the 2.6 orm module

**Comment by e-belair** [comment]
So what's up? Are you encountering some issues?

**Comment by kafoso** [comment]
Not so much of an issue per se. It has more to do with aesthetics and vulnerability concerns. PHP 5.6, for which Doctrine is written, has its end of life December 31, 2018. That's right around the corner.

If Doctrine changes to PHP ^7.1 syntax - which I definitely think it should - this library has to be overhauled completely in the future.

Additionally, a driver is written for the DBAL (https://github.com/doctrine/dbal). Not the ORM. In retrospect, the version number definitely should not follow the ORM, but rather the DBAL. Although, they are closely related.

The latest version is also no longer 2.6.

I'll look into it over the weekend.

**Comment by kafoso** [comment]
@manuscle 

Here you go: https://github.com/kafoso/doctrine-firebird-driver/releases/tag/2.6.0

Could you please have a go at it and get back to me? Thank you.

**Comment by e-belair** [comment]
I've just installed it on a Zend Framework 3 project and it seems to work great!
I'll play a while with it and come back to you if I encounter some issue.
Thank you very much for your work :-)

**Comment by kafoso** [comment]
You're welcome! Looking forward to getting some feedback.
