### ISSUE TITLE
Missing checkLastApiCall()

### ISSUE THREAD

**Issue by e-belair** [kafoso/doctrine-firebird-driver#4]
In case of sql error, i get the folling error:
Call to undefined method Kafoso\DoctrineFirebirdDriver\Driver\FirebirdInterbase\Statement::checkLastApiCall()

**Comment by e-belair** [comment]
I've made Connection::checkLastApiCall() public
Then I've modified Statement class, see my pull request...

**Comment by kafoso** [comment]
Great. Looks good at first glance. I'll check it later and ensure tests run correctly + add tests for the cases you've covered in PR https://github.com/kafoso/doctrine-firebird-driver/pull/5.

**Comment by kafoso** [comment]
PR https://github.com/kafoso/doctrine-firebird-driver/pull/5 has been merged.

I have, as mentioned, slightly improved exception handling and added more test coverage. See 20976ba33c485069beebb4a31b61425882195978.

There's a new release: [2.6.1](https://github.com/kafoso/doctrine-firebird-driver/releases/tag/2.6.1)

Thanks for your contribution.
