### ISSUE TITLE
Dialect parameter

### ISSUE THREAD

**Issue by mrysz** [kafoso/doctrine-firebird-driver#6]
In ibase_connect function, 6th parameter is for dialect select.

https://github.com/kafoso/doctrine-firebird-driver/blob/6457b43dc4107531a7c3f450c92809d8fb82a070/src/Driver/FirebirdInterbase/Connection.php#L423

By default it's 0 (autoselect), but if i want to force this value to be 3, I can't do that.

Mayby you can add in config something like this?

```
options:
    dialect: 3
```

**Comment by kafoso** [comment]
That's an oversight. I'll have a look at it.

**Comment by kafoso** [comment]
Fixed (in 389afcf62167499e74c22c8e85ad599cffed8e2c). Dialect is now applied in the constructor.

Applied to versions:

- [`2.5.3`](https://github.com/kafoso/doctrine-firebird-driver/releases/tag/2.5.3) (use with Doctrine 2.5)
- [`2.6.2`](https://github.com/kafoso/doctrine-firebird-driver/releases/tag/2.6.2) (use with Doctrine 2.6)
